package org.asite.automation.CommonLocators;

import org.asite.automation.common.config.ResourceHandler;
import org.openqa.selenium.By;

public class AdoddleModelsLocators {
	
	public static class ModelsTab {
		public static By	pop_ModelFileUploadActivityCentre							= By.cssSelector("div[id='fileUploadForModel'][style*='bottom'] div[class*='dashboard-box-top']");
		public static By	lbl_popActivityCentreHeader									= By.cssSelector("div[id='fileUploadForModel'][style*='bottom'] div[class*='dashboard-box-top'] div[class='widgetHeader']");
		public static By	ele_CustomizeModelListingOptions							= By.cssSelector("div[id='viewModels'] div[class*='listing-setting'] a[title='Settings']");
		public static By	lbl_BetaViewModelsViewModelViewerHeader						= By.cssSelector("div[class='main-header clearfix'] h1");
		public static By	lnk_ModelsAddModel											= By.cssSelector("div[id='left-nav-blocks'] a[id='leftAddModel']");
		public static By	css_ModelLists												= By.cssSelector("div[class*='innerContainer gray'] div[id='adTableBody'] div[index]");
		public static By	lnk_listModelName											= By.cssSelector("div[class*='userModelName']");
		public static By	pop_ModelsAddModel											= By.cssSelector("div[class='modal-scrollable'] div[id='myModal-modeladd'][style*='display: block']");
		public static By	lbl_PopAddModelHeader										= By.cssSelector("div[class='modal-scrollable'] div[id='myModal-modeladd'] h3[id='myModalLabel']");
		public static By	btn_PopAddModelSave											= By.cssSelector("div[id='myModal-modeladd'][style*='display: block'] div[class='modal-footer'] button[id='saveNewModel']");
		public static By	lbl_ModelAddSuccessMsg										= By.cssSelector("div[id='adoddleTopMsgBox'] span");
		public static By	opt_ModelProperties											= By.cssSelector("ul[class*='context-menu-list'] li[class='context-menu-item properties'] span");
		public static By	txt_popModelPropertiesTitle									= By.cssSelector("div[id='myModal-modeledit'][style*='display: block'] input[id='modelTitleEdit']");
		public static By	pop_ModelPropertiesEdit										= By.cssSelector("div[class='modal-scrollable'] div[id='myModal-modeledit'][style*='display: block']");
		public static By	drp_popModelPropertiesProject								= By.cssSelector("div[id='myModal-modeledit'][style*='display: block'] select[id='modelProjectEdit']");
		public static By	txt_popModelPropertiesDesc									= By.cssSelector("div[id='myModal-modeledit'][style*='display: block'] textarea[id='modelDescEdit']");
		public static By	txt_ModelPropertiesLongitude								= By.cssSelector("div[id='myModal-modeledit'][style*='display: block'] input[id='modelLongitudeEdit']");
		public static By	txt_ModelPropertiesLatitude									= By.cssSelector("div[id='myModal-modeledit'][style*='display: block'] input[id='modelLatitudeEdit']");
		public static By	txt_ModelPropertiesElevation								= By.cssSelector("div[id='myModal-modeledit'][style*='display: block'] input[id='modelElevationEdit']");
		public static By	btn_ModelPropertiesClose									= By.cssSelector("div[id='myModal-modeledit'][style*='display: block'] button[class='close']");
		public static By	lnk_ModelsListViewActive									= By.cssSelector("div[id='viewModels'] a[title='List View'][class*='active']");
		public static By	lnk_ModelsListView											= By.cssSelector("div[id='viewModels'] a[title='List View']");
		public static By	opt_ModelContextClickUpload									= By.cssSelector("ul[class*='context-menu-list'] li[class*= 'context-menu-item upload'] span");
		public static By	css_ModelsListingModels										= By.cssSelector("div[id='viewModels'] div[id='modelContentContainer'] div[id='adTableBody'] div[class*='rows']");
		public static By	drp_ModelsListingViewerRenderer								= By.cssSelector("div[id='viewModels'] select[id='renderer']");
		public static By	lnk_firstModelName											= By.cssSelector("div[id='modelContentContainer'] div[id='adTableBody'] div[class*='rows']:nth-child(1) div[class*='col-userModelName'] a");
		public static By	lnk_ModelViewerWorksetExpand								= By.cssSelector("div[id='folderTree'] div[class='tree-row'][style='padding-left:10px;'] a[class='hasChild glus']");
		public static By	lnk_BetaViewModelViewerWorksetExpand						= By.xpath(".//div[@class='default modelViewer']//span[contains(text(),'Show Model Tree')]");
		public static By	css_ModelViewerUploadedFiles								= By.cssSelector("div[id='modelBrowserWindow'] div[id='files-trees'] div[class*='rootModel'] div[class='tree-row'][style='padding-left:30px;'] a[class='docList'] span[class='tree-label']");
		public static By	lnk_ModelViewerFirstFileCollapse							= By.cssSelector("div[id='folderTree'] div[class*='docref-icon']:nth-child(1) div[class='tree-row'][style='padding-left:30px;'] a[class='hasChild glus']");
		public static By	scr_ServerRenderingViewerCanvasScreen						= By.cssSelector("div[id='modelViewTest'] div[id='content'] div[id='screen'] canvas[id='screen-canvas']");
		public static By	lbl_ViewIFCFileServerRenderingSuccessMessage				= By.cssSelector("canvas[id='screen-canvas']+div[class*='modelLoader']");
		public static By	img_ViewGridActiveView										= By.cssSelector("div[id='viewModels'] a[class='view-grid active']");
		public static By	img_ViewGridInActiveView									= By.cssSelector("div[id='viewModels'] a[class='view-grid']");
		public static By	opt_ModelViewerUploadedFirstFileLatestVersion				= By.cssSelector("div[id='modelBrowserWindow'] div[class*='docref-icon']:nth-child(1) div[class*='revision-icon']:nth-child(1) div[class='tree-row'][style*='left:50px'] span[class='tree-label']");
		public static By	lbl_ViewIFCFileLoadingSuccessMessage						= By.cssSelector("div[id='modelViewTest'] div[id='content'] div[id='screen'] div[class='alert alert-info pull-right modelLoader']");
		public static By	txt_filterModelInput										= By.xpath(".//div[@id='modelContentContainer']//form[@id='model_pd_filerForm']//input[@id='model_fd_containText']");
		/*public static By	bar_popActivityCentreUploadProgress							= By.cssSelector("div[id='fileUploadForModel'][style*='bottom'] div[class*='dashboard-box-top'] div[class='projectform'] div[class='bar'][style*='overflow: hidden']");
		public static By	img_popActivityCentreLoadingIcon							= By.cssSelector("div[id='fileUploadForModel'][style*='bottom'] div[class*='dashboard-box-top'] div[class='projectform'] div[class*='loading'] div[class='searchbox_ajax']");
		public static By	img_popActivityCentreMergingIcon							= By.cssSelector("div[id='fileUploadForModel'][style*='bottom'] div[class*='dashboard-box-top'] div[class='projectform'] div[class*='merging'] div[class='searchbox_ajax']");
		public static By	img_popActivityCentreMergedIcon								= By.cssSelector("div[id='fileUploadForModel'][style*='bottom'] div[class*='dashboard-box-top'] div[class='projectform'] div[class*='merging'] div[class*='icon-ok']");
		public static By	drp_ModelsViewModelViewerHeader								= By.cssSelector("div[id='modelViewer'] h2");
		public static By	chk_BetaViewModelViewerWorksetTreeCheckBox					= By.cssSelector("div[id='model-tree'] ul li:nth-child(2) ul li ul li ul li span[class='part detail loaded open'] i[class='tick']");
		public static By	ele_BetaViewModelViewerLoadingMsg							= By.cssSelector("div[class='alert alert-info pull-right modelLoader'] img");
		public static By	ele_BetaViewModelViewerLoadingSuccessfulMsg					= By.cssSelector("div[class='alert alert-info pull-right modelLoader']");
		public static By	btn_filterModel												= By.xpath(".//div[@id='modelContentContainer']//form[@id='model_pd_filerForm']//a[@id='modle_basic_search']");
		public static By	ele_ModelFilterResetAll										= By.cssSelector("div[class='container-fluid'] div[id='viewModels'] div[id='savedFilters'] li[listfilterkey='Active'] i[id='filterResetAll']");*/
		
		/* View Models */
		public static By	btn_ModelsTabViewModelViewsManager							= By.cssSelector("div[id='model-view-page'] div[class*='main-header'] button[title*='Views Manager']");
		public static By	css_ThumbViewModelsList										= By.xpath(".//div[@id='fourCol' and not(contains(@style,'display: none'))]//div[@index]//div[@class='box-projectname' and text()]");
		public static By	css_ListViewModelsList										= By.xpath(".//div[@id='listing' and contains(@style,'display: block')]//div[@index]//div[contains(@class,'userModelName')]//a[text()]");
		public static By	lnk_FavoriteModelsTab										= By.xpath(".//a[contains(@id,'FavoriteModel')]");
		public static By	lnk_ModelsTabFirstModel										= By.xpath(".//div[@index='0']//div[contains(@class,'userModelName')]//a");
		public static By	ele_ModelsTabListingHeaderAccessDate						= By.cssSelector("div[id='model-blocks'] div[class*='divthead '] span[id='lastAccessModelDate']");
		public static By	img_ModelsTabListingAccessDateAscending						= By.cssSelector("div[id='model-blocks'] div[class*='divthead '] span[id='lastAccessModelDate'] div[alt='Access Date - Sorted ascending']");
		public static By	lnk_ModelsTabLastModel										= By.cssSelector("div[id='model-blocks'] div[id='listing'] div[id='adTableBody'] div[class*='rows']:last-child div[class*='col-userModelName'] a");
		public static By	ele_ModelsTabThumbViewFirstModel							= By.xpath(".//div[@index='0']//div[@class='box-projectname']");
		public static By	lnk_AllModelsTab											= By.xpath(".//a[contains(@id,'AllModel')]");
		public static By	lnk_AddModelsTab											= By.xpath(".//a[contains(@id,'AddModel')]");
		public static By	ele_ModelsTabFavoriteModelsCount							= By.xpath(".//a[contains(@id,'FavoriteModel')]//span[text()]");
		public static By	css_UserModelNameList										= By.xpath(".//div[@index]//div[contains(@class,'userModelName')]//a[text()]");
		public static By	lnk_RecentModelsTab											= By.xpath(".//a[contains(@id,'RecentModel')]");
		public static By	ele_ModelsTabViewModelName									= By.xpath(".//div[@id='model-view-page']//h1//span[text()]");
		public static By	scr_ModelViewerCanvasScreen									= By.cssSelector("div[id='modelViewer'] div[id='hoopsWrapper'] div[id='screen'] div[id*='screen-canvas'] canvas");
		public static By	lbl_ViewIFCFileSuccessMessage								= By.xpath(".//div[@id='screen']//div[@class='alert alert-info pull-right modelLoader' and text()='Loading completed successfully']");
		public static By	img_FirstModelTypeIcon										= By.xpath(".//div[@index='0']//div[contains(@class,'modelTypeImagePath')]//img");
		public static By	css_ModelsTabOpenedModelIssueNumberList						= By.xpath(".//div[@id='content']//span[contains(text(),'WET')]");
		public static By	lnk_ModelsTabDisableNextPage								= By.xpath(".//div[contains(@id,'Paging')]//li[contains(@class,'disable') and @title='Next Page']//a");
		public static By	lnk_ModelsTabEnableNextPage									= By.xpath(".//div[contains(@id,'Paging')]//li[not(contains(@class,'disable')) and @title='Next Page']//a");
		public static By	lnk_ModelsTabFirstModelPublisher							= By.xpath(".//div[@index='0']//div[contains(@class,'publisher')]//a");
		public static By	lnk_ModelsTabFirstModelLastUpdatedUser						= By.xpath(".//div[@index='0']//div[contains(@class,'lastUpdatedBy')]//a");
		public static By	lnk_ModelsTabFirstModelLastAccessUser						= By.xpath(".//div[@index='0']//div[contains(@class,'lastAccessBy')]//a");
		public static By	ele_PopContactDetailsUser									= By.xpath(".//div[contains(@class,'card')][contains(@class,'open')]//h4[@title]");
		public static By	btn_PopContactDetailsCloseButton							= By.xpath(".//div[@id='contactDetailModal' and @aria-hidden='false']//button[@class='close']");
		public static By	txt_PopAddModelTitle										= By.xpath(".//div[@aria-hidden='false']//input[contains(@id,'modelTitle')]");
		public static By	txt_PopModelPropertiesModelTitleEdit						= By.cssSelector("form[id='formModelEdit'] input[id='modelTitleEdit']");
		public static By	txt_PopAddModelDescription									= By.xpath(".//div[@aria-hidden='false']//textarea[contains(@id,'modelDesc')]");
		public static By	drp_PopAddModelProject										= By.xpath(".//div[@aria-hidden='false']//select[@id='modelProject']");
		public static By	drp_PopAddModelUnits										= By.xpath(".//div[@aria-hidden='false']//select[@id='modelUnits']");
		public static By	btn_PopAddModelAddWorkSet									= By.xpath(".//a[contains(text(),'Add New Workset')]");
		public static By	pop_AddModelAddWorkSet										= By.xpath(".//div[@id='myModal-worksetsadd' and @aria-hidden='false']");
		public static By	txt_PopAddWorkSetName										= By.xpath(".//div[@aria-hidden='false']//input[@id='worksetName']");
		public static By	txt_PopAddWorkSetDiscipline									= By.xpath(".//div[@aria-hidden='false']//select[@id='worksetDiscipline']");
		public static By	lnk_PopAddWorkSetModelWorkSetTreeParent						= By.xpath(".//div[contains(@class,'tree-row')]//a[@class='docList first']//span[text()='All Workspace Documents']");
		public static By	lnk_PopAddWorkSetModelWorkSetTreeChild						= By.xpath(".//div[contains(@class,'tree-row')]//a[contains(@class,'docList')]//span[text()='ModelACLCheckFolder']");
		public static By	btn_PopAddWorkSetCreateFolder								= By.xpath(".//a[not(contains(@class,'disabled')) and contains(text(),'Create New Folder')]");
		public static By	btn_PopAddWorkSetCreateFolderLeftView						= By.xpath(".//a[contains(@class,'left open') and contains(text(),'Create New Folder')]");
		public static By	txt_PopAddWorkSetCreateFolderInput							= By.xpath(".//input[@id='createNewFolder']");
		public static By	btn_PopAddWorkSetSave										= By.xpath(".//div[@aria-hidden='false']//button[@id='saveWorksets' and contains(text(),'Save')]");
		public static By	txt_PopAddModelLongitude									= By.xpath(".//div[@aria-hidden='false']//input[contains(@id,'modelLongitude')]");
		public static By	txt_PopAddModelLatitude										= By.xpath(".//div[@aria-hidden='false']//input[contains(@id,'modelLatitude')]");
		public static By	txt_PopAddModelElevation									= By.xpath(".//div[@aria-hidden='false']//input[contains(@id,'modelElevation')]");
		public static By	drp_PopUploadModelFilesWorkset								= By.xpath(".//select[@id='worksetNameUpload']");
		public static By	btn_ModelUploadFileSelectFiles								= By.xpath(".//div[@aria-hidden='false']//span[contains(@class,'selectFilesModal')]/input");
		public static By	btn_ModelUploadfileUpload									= By.xpath(".//div[@aria-hidden='false']//button[@id='btnUploadFiles' and contains(text(),'Upload')]");
		public static By	lnk_PopModelUploadDashButton								= By.cssSelector("a[id='toggleModelUpload'][class='toggle-dash']");
		public static By	lnk_PopModelUploadPlusButton								= By.cssSelector("a[id='toggleModelUpload'][class='toggle-dash dash-toggle']");
		public static By	ele_ModelsTabFirstModelPublishDate							= By.xpath(".//div[@index='0']//div[contains(@class,'modelCreationDate')]");
		public static By	ele_ModelsTabFirstModelLastUpdateDate						= By.xpath(".//div[@index='0']//div[contains(@class,'lastUpdateDate')]");
		public static By	ele_ModelsTabFirstModelLastAccessDate						= By.xpath(".//div[@index='0']//div[contains(@class,'lastAccessModelDate')]");
		public static By	lnk_ModelsTabFirstModelThumbViewUploadFile					= By.xpath(".//div[@index='0']//div[@class='cover boxcaption']//a[contains(@class,'uploadfile')]");
//		public static By	lnk_ModelsTabFirstModelThumbViewViewFile					= By.xpath(".//div[@index='0']//div[@class='cover boxcaption']//a[@class='btn-mini btn btn-inverse']");
		public static By	lnk_ModelsTabFirstModelThumbViewViewFile					= By.xpath(".//div[@class='boxgrid']//div[@style='display: block;']//a[text()='View Model']");
		public static By	lnk_lnk_ModelsTabFirstModelThumbViewProperties				= By.xpath(".//div[@index='0']//div[@class='cover boxcaption']//a[contains(@class,'properties')]");
		public static By	btn_ClosePopupButton										= By.xpath(".//div[contains(@style,'display: block')]//button[text()='x']");
		/*
		public static By	btn_popActivityCentreOk										= By.cssSelector("div[id='fileUploadForModel'][style*='bottom'] div[class*='dashboard-box-top'] div[class='projectform'] div[class*='okbuton'] button");
		public static By	drp_ModelsTabViewer											= By.xpath(".//select[@id='renderer']");
		public static By ele_ModelsTabViewModelViewManager 							= By.cssSelector("div[id='model-view-page'] main[class='open'] h5");
		public static By drp_ModelsTabViewModelDiscussion 								= By.xpath(".//div[@id='model-view-page']//main[@class='open']//h5[(contains(text(),'Create Discussion'))]");
		public static By css_ModelsTabViewModelViewsList 								= By.cssSelector("div[id='model-view-page'] main[class='open'] div[class='views-container'] ul[class*='dd-list'] li[class*='dd-item']");
		public static By css_ModelsTabViewModelViewsListView 							= By.cssSelector("span[class*='fa-check'][title*='Create Comment']");
		public static By css_ModelsTabViewModelViewsListViewName 						= By.cssSelector("a[class*='view-name']");
		public static By btn_ModelsTabViewModelViewsDiscussion 						= By.cssSelector("div[id='model-view-page'] main[class='open'] div[class*='ibox-title'] span[class='action-btns'] button[title='Create Discussion']"* );
		public static By scr_browserRenderingViewerCanvasScreen 						= By.cssSelector("div[id='modelViewTest'] div[id='content'] div[id='screen'] canvas[id*='screen-canvas']");
		public static By scr_browserRenderingViewerCanvasScreen 						= By.cssSelector("div[id='modelViewer'] div[id='content'] div[id='screen'] canvas[id*='screen-canvas']");
		public static By drp_ModelsViewModelViewerRenderer 							= By.xpath(".//div[@id='modelViewer']//select[@id='renderer']");
		public static By ele_PopContactDetailsUser 									= By.xpath(".//div[@aria-hidden='false']//div[@id='contactDetailModalBody']//div[@class='contact-block']//h4[text()]");
		*/

		/* Create/download Model Comment & Model Form */
		public static By	btn_PopModelCommentAttachmentsAttachButton					= By.xpath(".//button[not(contains(@class,'disabled'))][text()='Attach']");
		public static By	css_PopAssociateFormsFormTitleList							= By.xpath(".//div[contains(@style,'display: block')]//div[@index]//div[contains(@class,'title')][text()]");
		public static By	css_BetaViewPopAssociateViewList							= By.xpath(".//association//div[contains(@class,'body')]//span[text()]");
		public static By	img_ViewModelFirstCommentAssociationsClipIcon				= By.xpath(".//div[contains(@id,'view-page')]//main[@class='open']//div[@class='ibox']//ul[contains(@ng-repeat,'index')][1]//li[contains(@ng-repeat,'index')]//div[@class='body']//a[contains(text(),'Attach & Assoc')]");
		public static By	lnk_PopAttachmentsAndAssociationsActiveTab					= By.xpath(".//div[contains(@style,'display: block')]//div[@id='pageLayoutHeader']//div[@id][contains(@class,'active')]//a");
		public static By	css_PopAttachmentsAndAssociationsAttachmentsTabFileNameList	= By.xpath(".//div[@aria-hidden='false']//div[@index]//div[contains(@class,'fileName')]//a");
		public static By	css_PopAttachmentsAndAssociationsFilesTabFileTypeImageList	= By.xpath(".//div[contains(@style,'display: block')]//div[@index]//div[contains(@class,'fileType')]//img");
		public static By	btn_ViewModelViewsCloseButton								= By.xpath(".//button[@id='updateClose']");
		public static By	btn_PopModelAttachmentsSelectFiles							= By.xpath(".//div[contains(@style,'display: block')]//span[contains(@class,'fileinput')]//input");
		public static By	ele_FormsLHTabFirstFormTitle								= By.xpath(".//div[@id='assocCommsList']//a[1]//div[@class='assocTitle'][text()]");
		public static By	ele_ViewFormsAttachIcon										= By.xpath(".//div[@id='accordion']//h4[contains(@id,'accordion')]//div[@class='attach divth']");
		public static By	lnk_ViewFormAttachment										= By.xpath(".//div[@class='assocHeader']//div[@id='Attachments']//a");
		public static By	txt_ViewModelViewInput										= By.xpath(".//input[@id='viewName']");
		public static By	chk_PopAttachmentAssociationCheckAllCheckbox				= By.xpath(".//div[contains(@style,'display: block')]//input[@class='checkall']");
		public static By	lnk_PopDownloadLink											= By.xpath(".//div[contains(@style,'display: block')]//a[text()='Download']");
		public static By	btn_PopDownloadButton										= By.xpath(".//div[contains(@style,'display: block')]//button[text()='Download']");
		public static By	css_AppendNameStringCheckList								= By.xpath(".//div[@class='othersContainer']//div/input[@type='checkbox']");
		public static By	pop_BatchFiles												= By.xpath(".//*[@id='myModal-downloadProgressBar' and @aria-hidden='false']");
		public static By	lnk_UploadIFCFileModel										= By.xpath(".//div[@index]//div[contains(@class,'ModelName')]//a[text()='"+ ResourceHandler.loadProperty("upload.ifc.model") + "']");
		/*public static By	lnk_CreateNewCommentTab										= By.xpath(".//a[contains(@id,'create-comment-model')]");
		public static By	btn_PopModelCommentAttachmentsSelectFiles					= By.xpath(".//div[@aria-hidden='false']//span[contains(@class,'fileinput')]//input");
		public static By	css_PopModelCommentAttachmentsAttachedFileNameList			= By.xpath(".//div[contains(@class,'create-comment')]//div[@class='tab-content']//div[contains(@class,'active')]//div[@class='gbody']//li[contains(@class,'gfname')]");
		public static By	css_PopModelCommentAttachmentsAttachedViewNameList			= By.cssSelector("div[class*='create-comment'] div[class='tab-content'] div[class*='active'] div[class='gbody'] ul[class='grow'] :nth-child(3)");
		public static By	css_ViewModelCommentActiveTab								= By.xpath(".//div[contains(@class,'create-comment')]//li[contains(@class,'active')]//uib-tab-heading");
		public static By	css_ViewModelCommentAttachmentTab							= By.xpath(".//div[contains(@class,'create-comment')]//li[not(contains(@class,'active'))]//uib-tab-heading[contains(text(),'Attachments')]");
		public static By	css_ViewModelCommentViewTab									= By.xpath(".//div[contains(@class,'create-comment')]//li[not(contains(@class,'active'))]//uib-tab-heading[contains(text(),'Views')]");
		public static By	txt_ViewModelCommentAttachmentSelectFile					= By.xpath(".//div[contains(@class,'upload-attach')]//span[contains(text(),'Select File (s)')]");
		public static By	pop_ModelCommentMoreOptionsPopup							= By.xpath(".//div[@id='moreoptions_Comment'][@aria-hidden='false']");
		public static By	lbl_ModelCommentMoreOptionsPopupLabel						= By.xpath(".//div[@id='moreoptions_Comment'][@aria-hidden='false']//h3");
		public static By	lnk_PopModelCommentOptionsAssociateFiles					= By.xpath(".//a[contains(@id,'assocDoc')]");
		public static By	lnk_PopModelCommentOptionsAssociateDiscussions				= By.xpath(".//a[contains(@id,'assocDiscussion')]");
		public static By	lnk_PopModelCommentOptionsAssociateForms					= By.xpath(".//a[contains(@id,'assocComms')]");
		public static By	lnk_PopModelCommentOptionsAssociateViews					= By.xpath(".//a[contains(@id,'assocViews')]");
		public static By	css_PopModelCommentOptionsAssociatedCheckList				= By.xpath(".//div[@aria-hidden='false']//div[@index]//div[contains(@class,'filelistchkbox')]//input");
		public static By	css_PopModelCommentOptionsAssociatedCheckList1				= By.xpath(".//div[contains(@style,'display: block')]//div[@index]//div[contains(@class,'filelistchkbox')]//input[not(contains(@filename,'Not Published'))]");
		public static By	css_PopAssociateDocsDocTitleList							= By.xpath(".//div[contains(@style,'display: block')]//div[@index]//div[contains(@class,'description')]//div[text()]");
		public static By	css_PopAssociateDiscussionsTitleList						= By.xpath(".//div[contains(@style,'display: block')]//div[@index]//div[contains(@class,'CommentTitle')]//div");
		public static By	css_PopSelectViewsProjectNameList							= By.xpath(".//div[contains(@class,'view-holder')]//div[not(contains(@class,'thumbnail-wrapper'))]");
		public static By	css_PopSelectViewsCheckList									= By.xpath(".//div[contains(@style,'display: block')]//input[contains(@class,'view')][@type='checkbox']");
		public static By	pop_AssociateViews											= By.xpath(".//div[contains(@id,'AssocViews')][contains(@style,'display: block')]");
		public static By	ele_ViewModelFirstCommentTitle								= By.xpath(".//div[@id='assocCommsList']//table[1]//td[@id='fRfT']//span[@id='ctitle'][text()]");
		public static By	css_PopAttachmentsAndAssociationsDiscussionsTabTitleList	= By.xpath(".//div[@aria-hidden='false']//div[@index]//div[contains(@class,'commentTitle')]//a");
		public static By	css_PopAttachmentsAndAssociationsViewsTabViewNameList		= By.xpath(".//div[@aria-hidden='false']//div[@index]//div[contains(@class,'viewName')]//a");
		public static By	lnk_CreateNewFormTab										= By.xpath(".//a[contains(@id,'create-form')]");
		public static By	lnk_ViewModelFirstCommentViewLink							= By.xpath(".//div[@id='assocCommsList']//table[1]//td[@id='comDesc']//a[@style='color:red;'][1]");
		public static By	btn_FirstDistributeUserDropdownToggleButton					= By.xpath(".//div[@class='distORICreation0false' and contains(@style,'block')]//ul[@class='select2-choices']//li[1]//button");
		public static By	btn_CreateFormAttachment									= By.xpath(".//div[@id='FormMoreOption' and not(contains(@style,'display:none'))]//button[text()='Attachment']");
		public static By	btn_ViewFormAttachment										= By.xpath(".//div[@class='viewFormMoreOption'][not(contains(@style,'display:none'))]//button[text()='Attachment']");
		public static By	btn_CreateFormMoreOptions									= By.xpath(".//div[@id='FormMoreOption' and not(contains(@style,'display:none'))]//button[text()='More Options']");
		public static By	btn_ViewModelAttachmentsSelectFiles							= By.xpath(".//div[contains(@class,'upload-attach')]//input[@id='inptFileUpload']");
		public static By	pop_ModelFormMoreOptionsPopup								= By.xpath(".//div[@id='moreoptions_form'][@aria-hidden='true']");
		public static By	lbl_ModelFormMoreOptionsPopupLabel							= By.xpath(".//div[@id='moreoptions_form'][@aria-hidden='true']//h3");
		public static By	btn_ModelAssociatePopupSaveButton							= By.xpath(".//div[contains(@style,'display: block')]//button[contains(text(),'Save')]");
		public static By	css_PopViewsProjectNameList									= By.xpath(".//div[contains(@style,'display: block')]//div[@id='assocViewsListing']//td[@class='filename'][text()]");
		public static By	lnk_UploadIFCModel											= By.xpath(".//div[@index]//div[contains(@class,'ModelName')]//a[text()='" + ResourceHandler.loadProperty("view.ifc.model") + "']");*/

		/* Sorting Locators */
		public static By	css_ModelsTabModelNameList									= By.xpath(".//div[@index]//div[contains(@class,'ModelName')]//a");
		public static By	css_ModelsTabModelCreationDateList							= By.xpath(".//div[@index]//div[contains(@class,'modelCreationDate')][text()]");
		public static By	css_ModelsTabModelUpdateDateList							= By.xpath(".//div[@index]//div[contains(@class,'lastUpdateDate')][text()]");
		public static By	css_ModelsTabModelAccessDateList							= By.xpath(".//div[@index]//div[contains(@class,'lastAccessModelDate')][text()]");
		public static By	css_ModelsTabLastModelAccessUserList						= By.xpath(".//div[@index]//div[contains(@class,'lastAccessBy')]//a");
	}
}