package org.asite.automation.CommonLocators;

import org.openqa.selenium.By;

public class ClassicDocListingLocators {

	public static class DocListingPage {
		public static By	frm_AsiteOptionsFrame							= By.cssSelector("frame[name='options']");
		public static By	frm_AsitePrefsFrame								= By.cssSelector("frame[name='prefHome']");
		public static By	img_DocListingAddToBasket						= By.xpath(".//div[@id='docSearchResult']//table//tbody//tr[4]//input[@title='Add to Basket']");
		public static By	img_DocListingViewBasket						= By.xpath(".//div[@id='docSearchResult']//table//tbody//tr[4]//input[@id='viewBasketIcon']");
		public static By	drp_DocListingBasketDocActions					= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] div[id='basketPanel'] table[class='searchBar'] tr[class='searchBar'] select[id='menu123'][class='backRed']");
		public static By	lbl_DocListingBatchPrintDocCount				= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] tr[valign='middle'] span[class*='red'] :nth-child(1)");
		public static By	lbl_DocListingBatchPrintDocPageTitle			= By.cssSelector("form[name='bottomsearch'] table[id='batch-print-table'] p[class='subtitle']");
		public static By	lbl_DocListingBatchPrintBasketPageTitle			= By.cssSelector("div[id='wrapper'] div[id='rh_content'] div[id='docSearchResult'] span[class='title']");
		public static By	chk_DocListingBatchPrintInclMarkUp				= By.cssSelector("form[name='bottomsearch'] table[id='batch-print-table'] input[name='doc_markup']");
		public static By	chk_DocListingBatchPrintInclChangeMark			= By.cssSelector("form[name='bottomsearch'] table[id='batch-print-table'] input[name='change_mark']");
		public static By	chk_DocListingBatchPrintFitToBanner				= By.cssSelector("form[name='bottomsearch'] table[id='batch-print-table'] input[name='fit_to_banner']");
		public static By	btn_DocListingBatchPrintDocPrintButton			= By.cssSelector("table[id='batch-print-table'] input[id='PrintDocs']");
		public static By	txt_DocListingDocRefInput						= By.cssSelector("div[id='docSearchPanel'] div[id='basicPanel'] input[id='docref']");
		public static By	chk_DocListingCheckAllChekbox					= By.xpath(".//tr[@class='trtableheading'][1]//input[@id='topCheck'][@type='checkbox']");
		public static By	txt_DocListingTitleInput						= By.cssSelector("div[id='wrapper'] div[id='docSearchPanel'] div[id='basicPanel'] input[id='description']");
		public static By	btn_DocListingSearch							= By.cssSelector("div[id='wrapper'] div[id='docSearchPanel'] div[id='basicPanel'] input[id='basicSearch']");
		public static By	css_DocListingDocRefList						= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg'][valign='top'] td[style*='word-break'] a[title*='Click here to view Document']");
		public static By	lbl_DocListingSearchResultsCount				= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] table[class='noborder'] tr[class='noborder'] td[class='noborder'] span[class='body1red']");
		public static By	css_DocListingDocRefListPublic					= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg'][valign='top'] td[style*='word-break'] span");
		public static By	lnk_DocListingFirstPOI							= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) td:nth-child(9)");
		public static By	lnk_DocListingFirstStatus						= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) a[title*='Click here to change status']");
		public static By	lnk_DocListingFirstDocRef						= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) a[class*='bodylink']");
		public static By	lnk_DocListingFirstDocRevision					= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) a[class*='revision_bold']");
		public static By	lnk_DocListingFirstAction						= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) a[title='Click here to complete the action']");
		public static By	lnk_DocListingFirstDocDistributionHistory		= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) a img[title='Click here to view Document Distribution history']");
		public static By	lnk_DocListingFirstDocTitle						= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) td:nth-child(8)");
		public static By	lnk_DocListingSecondDocTitle					= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(3) td:nth-child(8)");
		public static By	chk_DocListingFirstDocCheckbox					= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class='trbg1']:nth-child(2) input[id='docselect']");
		public static By	lnk_DocListingDownloadLink						= By.cssSelector("div[id='downloadDoc'] a[class='bodylink'] img[title*='Download]");
		public static By	img_DocListingFirstAttachmentIcon				= By.cssSelector("div[id='wrapper'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) a img[src*='i_attachment_head.gif']");
		public static By	btn_DownloadDocumentsDownload					= By.cssSelector("form[id='downloadFrm'] input[id='downloadbtn']");
		public static By	lbl_DownloadDocumentTitle						= By.cssSelector("form[id='downloadFrm'] td[class='subtitle']");
		public static By	chk_DownloadDocumentRebameWithDocRef			= By.cssSelector("form[id='downloadFrm'] tr[id='row_renameWithDocRef'] input[id='isRenameWithDocRef']");
		public static By	chk_DownloadDocumentAppendDocTitle				= By.cssSelector("form[id='downloadFrm'] tr[id='row_docTitle'] input[id='isAppendDocTitle']");
		public static By	chk_DownloadDocumentAppenedIssNo				= By.cssSelector("form[id='downloadFrm'] tr[id='row_issueNo'] input[id='isAppenedIssNo']");
		public static By	chk_DownloadDocumentAppenedRevNo				= By.cssSelector("form[id='downloadFrm'] tr[id='row_revNo'] input[id='isAppenedRevNo']");
		public static By	btn_DownloadDocumentZipDownload					= By.cssSelector("form[id='zipDownloadFrm'] input[id='btnDownload']");
		public static By	lbl_DocListingFolderPath						= By.cssSelector("div[id='wrapper'] div[id='docSearchPanel'] div[id='topPanel'] td[class='searchBar'] td[id='folderPath']");
		public static By	img_DocListingFolderMenu						= By.cssSelector("td[id='docSearchResultTD'] div[id='docSearchResult'] div[id='createFolder'] a img[id='imgFoldersMenu']");
		public static By	img_DocListingFolderMenuEditFolder				= By.cssSelector("div[id='divDocListMenus'] table[id='divFoldersMenuTable'] tbody img[title='Edit Folder']");
		public static By	img_DocListingFolderMenuMoveFolders				= By.cssSelector("div[id='divDocListMenus'] table[id='divFoldersMenuTable'] tbody img[title='Move Folders']");
		public static By	css_DocListingMoverFoldersFolderList			= By.cssSelector("div[id='docsCanMoveListingTd'][style*='block'] tr[class*='trbg'] td");
		public static By	css_DocListingSubFolderList						= By.cssSelector("div[id='folderTD'] div[id*='sublevel'] div[id*='sublevel'] table tbody tr td[class='closefolder'] a");
		public static By	css_DocListingSubFolderSubList					= By.cssSelector("div[id='folderTD'] div[id*='sublevel'] div[id*='sublevel'] div[id*='sublevel'] table tbody tr td[class='closefolder'] a");
		public static By	img_DocListingSubFolderMinus					= By.cssSelector("div[id='folderTD'] div[id*='sublevel'] img[src*='/images/minus.gif']");
		public static By	img_DocListingSubFolderSubMinus					= By.cssSelector("div[id='folderTD'] div[id*='sublevel'] div[id*='sublevel'] img[src*='/images/minus.gif']");
		public static By	img_DocListingSubFolderPlus						= By.cssSelector("div[id='folderTD'] div[id*='sublevel'] img[src*='/images/plus.gif']");
		public static By	img_DocListingSubFolderSubPlus					= By.cssSelector("div[id='folderTD'] div[id*='sublevel'] div[id*='sublevel'] img[src*='/images/plus.gif']");

		public static By	img_DocListingEditFolder						= By.xpath(".//div[@id='divFoldersMenu' and contains(@style,'display: block')]//table[@id='divFoldersMenuTable']//img[@title='Edit Folder']");

		/* Move Files */
		public static By	css_DocListingMovingFilesListDocRefs			= By.cssSelector("form[name='myForm'] div[id='docsCanMoveListingTd'] table[id='docsCanMoveListing'] tr[class*='trbg'] td:nth-child(5)");
		public static By	img_DocListingMenuPublishMenu					= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] tbody div[id='publish'] img[id='imgPublishDocuments']");
		public static By	img_DocListingMenuPublishStandardDoc			= By.cssSelector("div[id='divDocListMenus'] table[id='divPublishFormatTable'] tr:nth-child(1) div");
		public static By	lnk_DocListingEditFolderDirectAccess			= By.cssSelector("span[id='notificationLinkURLHref']");
		public static By	lbl_DocListingDirectAccessPageWorkspace			= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] tr[id='notificationDec'] td[nowrap='nowrap'] strong");
		public static By	chk_DocListingDirecAccessCheckAll				= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] td[class='userSearchListing'] table[id='docListTable'] input[id='topCheck']");
		public static By	btn_DocListingDirectAccessDownloadSelected		= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] tr[valign='top'] span[id='downloadBtns'] input[value='Download Selected']");
		public static By	lbl_PublishWindowPublishDocTitle				= By.cssSelector("td[class='title'] div[id='pub_title']");
		public static By	lnk_PublishWindowAddFiles						= By.cssSelector("form[id='form1'] div[id='divAddFiles'] div[id='divAddFileObj']");
		public static By	btn_PublishWindowEnterDocDetails				= By.cssSelector("form[name='uploaddoc'] div[id='enterdetail_div'] input[id='enterdetails']");
		public static By	rad_PublishWindowOverwrite						= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[id='radioApply'][value='OverWrite']");
		public static By	rad_PublishWindowMerge							= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[id='radioApply'][value='Merge']");
		public static By	img_DocListingMenuEditDocuments					= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] tbody div[id='link'] img[id='imgLinkDocuments']");
		public static By	img_DocListingMenuLinkDocument					= By.cssSelector("div[id='divDocListMenus'] table[id='divLinkDocsTable'] img[title='Link selected files to a new location']");
		public static By	img_DocListingMenuMoveDocuments					= By.cssSelector("div[id='divDocListMenus'] table[id='divLinkDocsTable'] img[title='Move Selected Documents']");
		public static By	lbl_LinkDocWindowSelectLocTitle					= By.cssSelector("form[name='linkfolder'] td[class*='title']");
		public static By	btn_LinkDocWindowCreateLink						= By.cssSelector("form[name='linkfolder'] input[id='submitbutton']");
		public static By	lbl_LinkSelectionWindowConfirmDocTitle			= By.cssSelector("form[name='linkSelection'] td[class='title']");
		public static By	btn_LinkSelectionWindowContinueLeft				= By.cssSelector("form[name='linkSelection'] input[id='btnContinueLeft']");
		public static By	drp_LinkSelectionWindowFirstLinkType			= By.cssSelector("form[name='linkSelection'] table[id='linkTab'] tr[class*='trbg']:nth-of-type(4) select[name='linkDocType']");
		public static By	lnk_DocDistributionViewCustomAttributesFirst	= By.cssSelector("form[name='frmBrava'] td[id='docInfo'] table:nth-child(1) tbody tr:nth-child(2) a[id='viewCustomAttribute']");
		public static By	css_DocAttributesAttribNames					= By.cssSelector("body table[cellspacing='1'] tr td:nth-child(1)");
		public static By	css_DocAttributesAttribValues					= By.cssSelector("body table[cellspacing='1'] tr td:nth-child(2)");
		public static By	lnk_DocumentDistributionAccessLink				= By.cssSelector("form[name='frmBrava'] div[id='links'] a[onclick*='ACCESS']");
		public static By	btn_FormLinkFolderCreateLinkButton				= By.cssSelector("form[name='linkfolder'] input[value='Create Link']");
		public static By	btn_FormMoveFoldersContinue						= By.cssSelector("form[name='frmMoveFolders'] input[value='Continue']");
		public static By	btn_FormMoveFilesContinue						= By.cssSelector("form[id='myForm'] input[name='btnMoveFilesContinue']");
		public static By	btn_FormMoveDocumentsContinue					= By.cssSelector("[name='moveDocuments'] input[name='btnMoveFiles']");
		public static By	btn_FormConfirmationOKButton					= By.cssSelector("input[value='OK']");

		/* Custom-Attributes */
		public static By	txt_PublishWindowHeaderRevision					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[id='revision']");
		public static By	txt_PublishWindowHeaderDocTitle					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[id='documentTitle']");
		public static By	drp_PublishWindowHeaderPOI						= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] select[id='purposeOfIssue']");
		public static By	drp_PublishWindowHeaderStatus					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] select[id='statusId']");
		public static By	txt_PublishWindowHeaderInteger					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='IntegerTextbox']");
		public static By	txt_PublishWindowHeaderEmail					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='EmailTextbox']");
		public static By	txt_PublishWindowHeaderDecimal					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='DecimalTextbox']");
		public static By	txt_PublishWindowHeaderLettersNumbers			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='LettersNumbersTextbox']");
		public static By	txt_PublishWindowHeaderLetters					= By.xpath(".//tr[@id='customAttributeFilterHeader']//input[contains(@headername,'Letter') and @valuerequired='true']");
		public static By	rad_PublishWindowHeaderRadioYes					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Radio'][value='1']");
		public static By	chk_PublishWindowHeaderMultiSelect1				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Multi selection checkbox'][id='custmAttrib_0_1011_0']");
		public static By	chk_PublishWindowHeaderMultiSelect2				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Multi selection checkbox'][id='custmAttrib_0_1011_1']");
		public static By	chk_PublishWindowHeaderMultiSelect3				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Multi selection checkbox'][id='custmAttrib_0_1011_2']");
		public static By	txt_PublishWindowHeaderDatePicker				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='DatePicker']");
		public static By	txt_PublishWindowHeaderCoordinatesOne			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Coordinates1Dimension']");
		public static By	txt_PublishWindowHeaderCoordinatesTwoX			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Coordinates2Dimension'][id='custmAttrib_0_1003_0']");
		public static By	txt_PublishWindowHeaderCoordinatesTwoY			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Coordinates2Dimension'][id='custmAttrib_0_1003_1']");
		public static By	txt_PublishWindowHeaderCoordinatesX				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Coordinates3Dimension'][id='custmAttrib_0_1004_0']");
		public static By	txt_PublishWindowHeaderCoordinatesY				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Coordinates3Dimension'][id='custmAttrib_0_1004_1']");
		public static By	txt_PublishWindowHeaderCoordinatesZ				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] input[headername*='Coordinates3Dimension'][id='custmAttrib_0_1004_2']");
		public static By	drp_PublishWindowHeaderStates					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] select[headername*='States']");
		public static By	drp_PublishWindowHeaderCities					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] select[headername*='Cities']");
		public static By	btn_PublishWindowHeaderApplyToAll				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable'] tr[id='customAttributeFilterHeader'] div[class='btn_applytoall']");
		public static By	btn_PublishWindowStartUpload					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] div[id='uploadBtns'] input[id='startUpload']");
		public static By	btn_PublishWindowSimpleUploadStartUpload		= By.cssSelector("div[id='content'] td[class='title'] input[id='startUploadBTN']");
		public static By	ele_PublishWindowAttributesSection				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='publishdocTable']");
		public static By	txt_PublishWindowAttributesFirstRev				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='revision1']");
		public static By	txt_PublishWindowAttributesSecondRev			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='revision2']");
		public static By	txt_PublishWindowAttributesFirstDocRef			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='docRef1']");
		public static By	txt_PublishWindowAttributesSecondDocRef			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='docRef2']");
		public static By	txt_PublishWindowAttributesFirstDocTitle		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] textarea[id='documentTitle1']");
		public static By	txt_PublishWindowAttributesSecondDocTitle		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] textarea[id='documentTitle2']");
		public static By	drp_PublishWindowAttributesFirstPOI				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] select[id='purposeOfIssue1']");
		public static By	drp_PublishWindowAttributesSecondPOI			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] select[id='purposeOfIssue2']");
		public static By	drp_PublishWindowAttributesFirstStatus			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] select[id='statusId1']");
		public static By	drp_PublishWindowAttributesSecondStatus			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] select[id='statusId2']");
		public static By	txt_PublishWindowAttributesFirstInteger			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1008']");
		public static By	txt_PublishWindowAttributesSecondInteger		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1008']");
		public static By	txt_PublishWindowAttributesFirstEmail			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1007']");
		public static By	txt_PublishWindowAttributesSecondEmail			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1007']");
		public static By	txt_PublishWindowAttributesFirstDecimal			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1006']");
		public static By	txt_PublishWindowAttributesSecondDecimal		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1006']");
		public static By	txt_PublishWindowAttributesFirstLetterNumber	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1010']");
		public static By	txt_PublishWindowAttributesSecondLetterNumber	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1010']");
		public static By	txt_PublishWindowAttributesFirstLetter			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1009']");
		public static By	txt_PublishWindowAttributesSecondLetter			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1009']");
		public static By	txt_PublishWindowAttributesFirstDatePicker		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1005']");
		public static By	txt_PublishWindowAttributesSecondDatePicker		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1005']");
		public static By	rad_PublishWindowAttributesFirstRadioYes		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1012_0']");
		public static By	rad_PublishWindowAttributesSecondRadioYes		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1012_0']");
		public static By	txt_PublishWindowAttributesFirstCoordinate1		= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1002_0']");
		public static By	txt_PublishWindowAttributesSecondCoordinate1	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1002_0']");
		public static By	txt_PublishWindowAttributesFirstCoordinate2X	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1003_0']");
		public static By	txt_PublishWindowAttributesSecondCoordinate2X	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1003_0']");
		public static By	txt_PublishWindowAttributesFirstCoordinate2Y	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1003_1']");
		public static By	txt_PublishWindowAttributesSecondCoordinate2Y	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1003_1']");
		public static By	txt_PublishWindowAttributesFirstCoordinate3X	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1004_0']");
		public static By	txt_PublishWindowAttributesSecondCoordinate3X	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1004_0']");
		public static By	txt_PublishWindowAttributesFirstCoordinate3Y	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1004_1']");
		public static By	txt_PublishWindowAttributesSecondCoordinate3Y	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1004_1']");
		public static By	txt_PublishWindowAttributesFirstCoordinate3Z	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='custmAttrib_2_1004_2']");
		public static By	txt_PublishWindowAttributesSecondCoordinate3Z	= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='custmAttrib_3_1004_2']");
		public static By	drp_PublishWindowAttributesFirstState			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] select[id='custmAttrib_2_1013']");
		public static By	drp_PublishWindowAttributesSecondState			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] select[id='custmAttrib_3_1013']");
		public static By	drp_PublishWindowAttributesFirstCity			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] select[id='custmAttrib_2_1001']");
		public static By	drp_PublishWindowAttributesSecondCity			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] select[id='custmAttrib_3_1001']");
		public static By	drp_PublishWindowAttributesDistribute			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] table[id='distTable'] div[id='distributionDiv'] select[id='distListId']");
		public static By	btn_PublishWindowAttributesFirstBrowse			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg1'] input[id='attach_file1']");
		public static By	btn_PublishWindowAttributesSecondBrowse			= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] tr[class='trbg2'] input[id='attach_file2']");
		public static By	ele_PublishWindowUploadSuccessTable				= By.cssSelector("div[id='uploadProcess'] table[id='successTable']");
		public static By	btn_PublishWindowUploadSuccessOk				= By.cssSelector("div[id='uploadProcess'] input[type='button']");
		public static By	btn_PublishWindowCopyFileName					= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] input[id='copyfilename']");
		public static By	img_PublishWindowDocDistribution				= By.cssSelector("form[name='uploaddoc'] div[id='docsinforow'] div[id='distUsersDiv'] span[id='distLinkEnable'] a img[title='Add further recipients']");
		public static By	lnk_PrefsWindowUploadPrefs						= By.cssSelector("a[id='uploadLink']");
		public static By	rad_PrefsWindowStandardPublish					= By.cssSelector("form[id='myForm'] table[id='uploadTbl'] input[type='radio'][value='1']");
		public static By	btn_PrefsWindowUploadPrefSubmit					= By.cssSelector("form[id='myForm'] table[id='uploadTbl'] input[id='download32'][type='submit']");

		public static By	lbl_ParentDocListFolderPath						= By.xpath(".//div[@id='topPanel' and @style='display:block;']//td[@id='folderPath' and text()]");
		public static By	lnk_CreateParentFolder							= By.xpath(".//div[@id='wrapper']//table//tbody//div[@id='createParentFolder']//a[contains(@onclick,'createTopFolder')]");
		public static By	lbl_CreateFolderPageTitle						= By.xpath(".//form[@name='createFolder']//td[@class='title']");
		public static By	txt_CreateFolderInput							= By.xpath(".//input[@id='folderName']");
		public static By	drp_CreateFolderRoleSelect						= By.cssSelector("form[name='createFolder'] td[class='subtitle'] select[id='rolesa']");
		public static By	btn_CreateFolderRolesSubmit						= By.cssSelector("form[name='createFolder'] td[class='subtitle'] input[id='RolesSubmit']");
		public static By	drp_CreateFolderRolesValueDropdown				= By.cssSelector("form[name='createFolder'] div[id='selectedRoles'] select[id*='role']");
		public static By	btn_CreateFolder								= By.xpath(".//input[@id='CreateFolder']");
		public static By	txt_CreateEditFolderInput						= By.xpath(".//input[@id='folderNameEdit']");
		public static By	btn_CreateFolderUpdateChanges					= By.xpath(".//input[@id='UpdateChanges']");
		public static By	img_DeactivateFolderClearActions				= By.cssSelector("form[name='frm'] tr[id='docsheader'] table[id='DocClearAction'] a[onclick*='docclearordelegateActions'] img[src*='clear_doc_action']");
		public static By	chk_DeactivateFolderSelect						= By.xpath(".//*[@id='isActive' and @type='checkbox']");
		public static By	lbl_DeactivateFolderTitle						= By.xpath(".//div[@id='folderMessage']//td[@class='title' and text()]");
		public static By	btn_CreateFolderContinue						= By.xpath(".//div[@id='folderMessage']//input[@type='button' and @name='Continue']");
		public static By	btn_DeactivateFolderClearActionsContinue		= By.cssSelector("input[id='continue']");
		public static By	lnk_AllWorkspaceDocuments						= By.cssSelector("div[id='folderTD'] a[id*='link'][title='All Workspace Documents']");
		public static By	css_NumberOfFiles								= By.xpath(".//*[@id='docListTable']//tr[contains(@class,'trbg')]");
		public static By	lnk_DocListingFirstFileDocRef					= By.cssSelector("form[name= 'bottomsearch'] a[title*='Click here to view Document']");
		// public static By lnk_DocListingFirstFileDocRef = By.xpath(".//table[@id='docListTable']//tr[2]//a[contains(@title,'Click here to view Document')]");
		public static By	lbl_DocListingFirstFileDocTitle					= By.xpath(".//table[@id='docListTable']//tr[2]//td[7]");
		public static By	frm_AsiteViewDocument							= By.xpath(".//frameset[@id='bravaDocViewer']//frame[contains(@name,'viewdocument')]");
		public static By	frm_BravaObjectFrame							= By.xpath(".//div[@id='container']//object[contains(@id,'brava-viewer')]");
		public static By	frm_OpenFileIframe								= By.xpath(".//div[@id='dijit__WidgetBase_0']//iframe");
		public static By	frm_ViewDocumentLeftPanel						= By.xpath(".//frameset[@id='bravaDocViewer']//frame[@name='left_panel']");
		public static By	frm_ViewDocumentBravaLeftPanel					= By.xpath(".//frameset//frame[@name='brava_left_panel']");
		public static By	lbl_ViewDocumentDocRef							= By.xpath(".//table[@id='tbldocdetail']//tr[3]//span");
		public static By	lbl_ViewDocumentDocTitle						= By.xpath(".//table[@id='tbldocdetail']//tr[4]/td[text()]");
		public static By	frm_ViewDocumentDummyFrame						= By.xpath(".//form[@name='DocumentView']//iframe[@id='dummyFrm']");
		public static By	frm_ViewDocumentBravaApplet						= By.xpath(".//form[@name='DocumentView']//object[@name='bravaApplet']");
		public static By	lbl_ParentDocListParentFolderPath				= By.xpath(".//div[@id='topPanel' and @style='display:block;']//td[@id='folderPath' and text() and not(contains(@title,'AutoMoveTestFolder1'))]");
		public static By	lbl_AccessHistoryLatestRemarks					= By.xpath(".//table[@id='tblDocInfoAccess']//tr[2]//td[@class='wbr']");
		public static By	lbl_AccessHistoryLatestAccessDateTime			= By.xpath(".//table[@id='tblDocInfoAccess']//tr[2]//td[@class='body1red' and @align='center']//span[text()]");

		public static By	lnk_DocListingAdvanceSearch						= By.xpath(".//div[@id='advanceImage']//a");
		public static By	txt_DocListingAdvanceSearchFileName				= By.xpath(".//div[@id='advancePanel' and not(contains(@style,'display: none;'))]//input[@id='filename']");
		public static By	btn_DocListingAdvanceSearch						= By.xpath(".//input[@id='Search' and @type='button']");
		public static By	lnk_DocListingBasicSearch						= By.xpath(".//div[@id='basicImage' and not(contains(@style,'display: none'))]//a");
		public static By	lnk_DocListingHistoryFileName					= By.xpath(".//td[@id='docInfo']//table//tr[3]//td[contains(@class,'body1red')]//a[@title='Click here to view revision']");
		public static By	chk_DocListingSecondDocCheckbox					= By.xpath(".//table[@id='docListTable']//tr[3]//input[@id='docselect']");
		public static By	img_DocListingLinkDocuments						= By.xpath(".//a//img[@id='imgLinkDocuments']");
		public static By	lnk_DocListingCompareDocuments					= By.xpath(".//table[@id='divLinkDocsTable']//img[@alt='Compare Documents']");
		public static By	lnk_DocListingCompareDocumentsImage				= By.cssSelector("div[id='compareDoc'] img[src*='i_compare.gif']");
		public static By	frm_CompareDocumentIFrame						= By.xpath(".//frameset[@id='bravaDocViewer']//frame[contains(@name,'comparedocument')]");
		public static By	ele_CompareFilesViewerElement					= By.xpath(".//div[@id='BXControl' and contains(@style,'width: 98%')]");
		public static By	frm_CompareFilesViewerIFrame					= By.xpath(".//div[@id='BXControl']//object[@id='beaxv0']");
		public static By	chk_AllWorkSpaceDocsTopCheckBOx					= By.cssSelector("table[id='docListTable'] tr[class='trtableheading']:nth-child(1) input[id='topCheck']");
		public static By	chk_FirstFileSelectCheckBOx						= By.cssSelector("tr[class='trbg1'] td div input[id*='docselect'][type='checkbox']");
		public static By	chk_SecondFileSelectCheckBOx					= By.cssSelector("tr[class='trbg2'] div[align='center'] input[id*='docselect'][type='checkbox']");

		/* Download-Files */
		public static By	img_DocListingFirstFileTypeIcon					= By.cssSelector("div[id='wrapper'] div[id='docSearchResult'] td[class='userSearchListing'] table[id='docListTable'] tr[class*='trbg']:nth-child(2) img[title*='Click here to download the File']");
		public static By	css_DocListigHistoryAttachFilesList				= By.xpath(".//div[@id='extdocList']//a[text()]");
		public static By	img_DocListingDownloadSelectedDocumentsButton	= By.xpath(".//img[@title='Download Selected Documents']");
		public static By	css_DownloadDocumentsCheckboxList				= By.xpath(".//table//input[@type='checkbox']");
		public static By	btn_DownloadDocumentsInvisiableZipDownload		= By.xpath(".//input[@id='btnDownload' and @disabled='true']");
		public static By	btn_DownloadDocumentsVisibleZipDownload			= By.xpath(".//input[@id='btnDownload' and not(contains(@disabled,'true'))]");
		public static By	chk_DownloadDocumentParentDocument				= By.xpath(".//input[@id='isParentDoc']");
		public static By	chk_DownloadDocumentAssociatedFiles				= By.xpath(".//input[@id='isAssocFiles']");
		public static By	chk_DownloadDocumentAssociatedDocuments			= By.xpath(".//input[@id='isAssociatedDocuments']");
		public static By	chk_DownloadDocumentAttachedDocuments			= By.xpath(".//input[@id='isAttachedDocuments']");
		public static By	chk_DownloadDocumentExtractFilesDownload		= By.xpath(".//input[@id='isExtractFiles']");
		public static By	btn_DownloadDocumentBrowse						= By.xpath(".//div[@id='browseTr' and not(contains(@style,'hidden'))]//input[@id='Browse']");
		public static By	lbl_DownloadDocumentExtractFiles				= By.xpath(".//div[@id='downloadApplet' and not(contains(@style,'display:none'))]//span[@id='statusExtract' and text()='Extracting Files...']");
		public static By	frm_DownloadApplet								= By.xpath(".//div[@id='downloadApplet' and @style='DISPLAY: block']//object[@id='downloader']");

		/* Create-Comment */
		public static By	lbl_CreateNewCommentHeader						= By.cssSelector("form[name='commentPage'] span[class='subtitle'] div[id='displayTitle']");
		public static By	txt_CreateCommentTitleInput						= By.cssSelector("form[name='commentPage'] input[id='commTitle'][type='text']");
		public static By	txt_CreateCommentCommentInput					= By.cssSelector("form[name='commentPage'] textarea[id='commText']");
		public static By	lnk_CreateCommentDocDistribution				= By.cssSelector("form[name='commentPage'] div[id='distributionDivTag'] a[class='bodylink'][onclick*='openDistribution'] strong");
		public static By	lbl_CreateCommentDistributionSingleRecipient	= By.cssSelector("form[name='commentPage'] table[id='distTable'] tr[class='trbg1'] td:nth-child(4)");
		public static By	lnk_CreateCommentAddDocFolder					= By.cssSelector("form[name='commentPage'] tr[id='assocDocsTD'] a[title='Add Docs from Folders']");
		public static By	lnk_CreateCommentAddForms						= By.cssSelector("form[name='commentPage'] a[title='Add Forms']");
		public static By	img_CreateCommentAttachExternalDoc				= By.cssSelector("form[name='commentPage'] td[class='print'] img[title='Attach External Documents']");
		public static By	lnk_CreateCommentAttachExternalDoc				= By.cssSelector("form[name='commentPage'] tr[id='attachDocTD'] a[class='bodylink'][onclick*='openAttachDocs'] strong");
		public static By	btn_CreateCommentSendTop						= By.cssSelector("form[name='commentPage'] input[id='sendTop']");
		public static By	lbl_CreateCommentListingTableFirstComment		= By.cssSelector("form[name='frmBrava'] td[id='docInfo'] tr[class*='trbg']:nth-child(1) table[class='tblCommentsTree']:nth-of-type(1) div[id*='comHeader']");
		public static By	lbl_CreateCommentDetailsCommentTitle			= By.cssSelector("form[name='commentConfirm'] tr[class='trtableheading'] td[class='trtableheading']:nth-child(2)");
		public static By	css_CreateCommentDetailsAssociatedDocs			= By.cssSelector("form[name='commentConfirm'] div[id='docsList'] table[id='assocDocList'] tr[class*='trbg'] td:nth-child(4)");
		public static By	css_CreateCommentDetailsAssociatedForms			= By.cssSelector("form[name='commentConfirm'] div[id='formsList'] table[id='formSearchResultTable'] tr[class*='trbg'] td:nth-child(3)");
		public static By	css_CreateCommentDetailsAttachedDocs			= By.cssSelector("form[name='commentConfirm'] div[id='extdocList'] table tr[class*='trbg'] td:nth-child(3)");

		/* Manage Configurable Attributes */
		public static By	tab_CreateCustomAttributesSet					= By.cssSelector("div[id='pageWrapper'] td[id='attributeSetsTab']");
		public static By	lnk_EditCustomAttributesSetFirstEditLink		= By.cssSelector("div[id='projectCustomAttributeList'] form[name='myForm'] tr[class*='trbg']:nth-child(2) td:nth-child(3) a");
		public static By	lnk_EditCustomAttributesSetStaticEditLink		= By.cssSelector("div[id='projectCustomAttributeList'] form[name='myForm'] tr[class*='trbg']:nth-child(3) td:nth-child(3) a");
		public static By	frm_CreateCustomAttributeFrame					= By.cssSelector("iframe[id='iFrmCreateCustomAttribute']");
		public static By	css_CreateCustomAttributeSetFolderList			= By.cssSelector("div[id='divSelectFolderTree'] div[id='displayFolderTree'] div[id*='sublevelSrc'] a td[nowrap='nowrap'] a");
		public static By	btn_CreateCustomAttributeSetSave				= By.cssSelector("div[id='pageWrapper'] form[name='createAttribSetForm'] input[id='btnSave']");

		/* Applet-Upload */
		public static By	lnk_CustomAttributesFolder						= By.xpath(".//a[contains(text(),'CustomAttributes')]");
		public static By	img_DocListingPublishDocMenu					= By.cssSelector("td[id='docSearchResultTD'] div[id='docSearchResult'] div[id='publish'] a");
		public static By	lnk_PublishDocumentPublishPageAppletUploadLink	= By.xpath(".//td[@class='uploadTab']//a//b[text()='here']");
	}

}